--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JackNoordhuis/Battles
branches:
- master
projects:
  Battles:
    path: ""
    libs:
      - src: JackNoordhuis/framework/container
        version: 5.6.5
      - src: JackNoordhuis/framework/support
        version: 5.6.5
...
