name: Battles
description: Extremely configurable and extendable plugin that allows you to create fair battles between players!
version: 0.0.1_ALPHA-dev#5
author: Jack Noordhuis
main: jacknoordhuis\battles\BattlesLoader
api: 3.0.0-ALPHA10