# Battles plugin v0.0.1_ALPHA-dev#2 for PocketMine-MP – Settings.yml configuration file
#
# Should we cache arena data once the config has been read (reduces startup time)? You can clear the cache at anytime
# by deleting the data/arenas.cache.sl file.
cache-arena-data: yes